### PR TITLE
add DeepTau and DeepMet models to sonic model repository

### PR DESCRIPTION
**Pull request by yongbinfeng**
This PR adds the DeepTau and DeeMET models.

The DeepMET model is a tensorflow model with inputs of pf candidates (fixed length of 4.5K candidates per event), and outputs the MET in the x and y direction

The DeepTau is an ensemble model, including 4 models: the inner and outer models for inner and outer grid cells, the python custom backend to map the itau, ieta, iphi of each input cell to the core network, and the core model to run the Convolution on inner grids, outer grids, and tau inputs. All the three ML models are TF models.

Note python custom backend is only supported from Triton server version 20.10:
https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_20-10.html

### CODE REVIEW

**Comment by kpedro88** [comment]
Is it necessary to keep the file `models/deeptau_python/1/__pycache__/model.cpython-38.pyc` in the repo?

**Comment by yongbinfeng** [comment]
sorry this is a mistake. updatad and deleted the pycache now.

**Comment by kpedro88** [comment]
please squash the branch so it doesn't enter the history

**Comment by yongbinfeng** [comment]
Currently for DeepMet we have two tunings and they are both running for miniAOD. I put these into two model versions here in the same model directory. 

Would it be better to create two separate model directories with two model configs, or better to keep it this way as two model versions?

**Comment by kpedro88** [comment]
since they use the same config.pbtxt, i think it's fine to have them as two model versions.

**Pull request merged**
